name: Makefile CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        override: true
    
    - uses: actions/setup-node@v3
      with:
        node-version: 16
      
    - name: Install dependencies
      run: make
