name: Makefile CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths:
      - "src/styles/**/*"
      - "src/scripts/**/*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
      with:
        node-version: 16
      
    - name: Build project
      run: make
