name: Publish

on:
  push:
    branches:
      - 'main'
      - 'action'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Get dependencies
        run: npm ci

      - name: Transpile
        run: npm run compile

      - name: Publish current workdir (which contains generated content) to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.2

        with:
          source-directory: .
          target-branch: gh-pages
