name: Publish

on:
  push:
    branches:
      - 'main'
      - 'action'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Get dependencies and transpile
        run: npm ci

      - name: Publish
        uses: rayluo/github-pages-overwriter@v1.2

        with:
          source-directory: .
          target-branch: gh-pages
